Added kms CMK support for ecs
sourcefuse/terraform-aws-arc-ecs pull request #67
Opened 2024-07-12 08:44 UTC by mayank0202

## Description

Added kms CMK support for ecs

## Related Issue

- [Issue Number](link-to-issue): Brief description

## Checklist

Please ensure that the following steps are completed before submitting the pull request:

- [x] Code follows the Terraform best practices and style guidelines.
- [ ] Changes are appropriately documented, including any necessary updates to README or other documentation files.
- [ ] Unit tests have been added or updated to cover the changes introduced by this pull request.
- [x] Changes have been tested locally and verified to work as expected.
- [x] The code has been reviewed to ensure it aligns with the project's goals and standards.
- [x] Dependencies and backward compatibility have been considered and addressed if applicable.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Testing Instructions

Ran example folder and it deployed all resources perfectly , nothing is a breaking change

2024-07-12 08:47 UTC, mayank0202 commented
@tsaucier-sf  as per discussion we don't have functionality for  ECS Fargate ephemeral storage

[issues-aws-provider](https://github.com/hashicorp/terraform-provider-aws/issues/37922)

Currently only `execute_command_configuration` is allowed in an ECS cluster configuration in Terraform which i have added  in this PR

2024-07-15 10:03 UTC, vijay-stephen requested changes

2024-07-15 10:03 UTC, vijay-stephen commented on variables.tf
> +variable "enabled" {
This variable is not required. instead use `kms_key_arn` defaulted to null

2024-07-15 10:03 UTC, vijay-stephen commented on variables.tf
> +}
Use `kms_key_arn` defaulted to null,

null / non-null to enable disable

2024-07-15 10:03 UTC, vijay-stephen commented on main.tf
> +  enabled                 = var.enabled
please don't use this variable.

2024-10-04 18:17 UTC, closed without merging